### ISSUE TITLE
ARP attributes names

### ISSUE THREAD

**Issue by tvdijen** [OpenConext/OpenConext-manage#16]
I'm having an issue with the way attributes are displayed in the ARP-tab..
Let's say we have the following configuration in `metadata_configuration/saml20_sp.schema.json`:

```
            "urn:example.org:customer-x:app-x:employeeId": {
              "$ref": "#/definitions/ArpAttribute",
              "alias": "urn:oid:a.b.c"
            },
            "urn:example.org:customer-y:app-y:employeeId": {
              "$ref": "#/definitions/ArpAttribute",
              "alias": "urn:oid:k.l.m"
            },
```

Both attributes will be displayed in the ARP-tab as `employeeId` because of the following line of code:
https://github.com/OpenConext/OpenConext-manage/blob/c52067b827157408b6f60a5f0f48dad0adfbb0ee/manage-gui/src/components/metadata/ARP.jsx#L50

Now, I know this could be solved by standardizing attributes, but that's just now how my clientele's boats float.. It would be very nice to have a way to provide a displayName for attributes, so I can see the full attribute name instead of the cutoff version. Could be a configuration setting to not cutoff any names at all, to keep it simple stupid

**Comment by oharsta** [comment]
A new property was introduced in the ARP definition: `display`. If present then this property is used in both the sorting and the display of the ARP attribute. It was introduced when we added the ARP attribute `urn:mace:eduid.nl:1.1` which broke the `nameOfKey` algorithm. With the `display` property your use-case can be resolved. See https://github.com/OpenConext/OpenConext-manage/blob/master/manage-gui/src/components/metadata/ARP.jsx#L50

**Comment by tvdijen** [comment]
Awesome, thanks!
