### ISSUE TITLE
References to attribute_aggregation_required

### ISSUE THREAD

**Issue by tvdijen** [OpenConext/OpenConext-manage#18]
There are still a bunch of references to the setting 'attribute_aggregation_required', which was removed from EB in 5.7.2.
https://github.com/OpenConext/OpenConext-manage/search?q=attribute_aggregation_required&unscoped_q=attribute_aggregation_required

**Comment by oharsta** [comment]
Fixed in https://github.com/OpenConext/OpenConext-manage/commit/4f61bf5552c29244c36d4c7f515237eca8ec977f
