### ISSUE TITLE
Feature request: add additional states by configuration

### ISSUE THREAD

**Issue by tvdijen** [OpenConext/OpenConext-manage#25]
It would be really nice to be able to add additional states without having to manipulate code.
Right now, I have to edit `manage-gui/src/components/metadata/SelectState.jsx`, add translations for in in `manage-gui/src/locale/en.js` and rebuild..

**Comment by thijskh** [comment]
My idea is to get rid of workflow states instead. Something to discuss on the mailinglist I think.
