### ISSUE TITLE
4.0.11: Unexpected Error on metadata import

### ISSUE THREAD

**Issue by tvdijen** [OpenConext/OpenConext-manage#26]
I recently upgraded from 3.2.13 to 4.0.11 and ran into an 'Unexpected error' while importing XML metadata of an AD FS IDP. Rolling back to 3.2.13 solved the issue, so something must have changed between those versions. I haven't had the time to further pinpoint this.

From the server logs:

> Nov  4 14:25:34 MANAGE-DWR: [http-nio-9393-exec-1] org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping Returning handler method [public org.springframework.http.ResponseEntity<java.util.Map<java.lang.String, java.lang.Object>> manage.control.ErrorController.error(javax.servlet.http.HttpServletRequest)]
> Nov  4 14:25:34 MANAGE-DWR: [http-nio-9393-exec-1] org.springframework.beans.factory.support.DefaultListableBeanFactory Returning cached instance of singleton bean 'errorController'
> Nov  4 14:25:34 MANAGE-DWR: [http-nio-9393-exec-1] org.springframework.web.servlet.mvc.method.annotation.HttpEntityMethodProcessor Written [{timestamp=Mon Nov 04 14:25:34 CET 2019, status=500, error=Internal Server Error, exception=java.lang.NullPointerException, path=/manage/api/client/import/xml/saml20_idp}] as "application/json" using [org.springframework.http.converter.json.MappingJackson2HttpMessageConverter@57ac5227]

**Comment by oharsta** [comment]
Can you attach the XML to this issue? And the server logs should contain more information: e.g. the complete stack-trace.

**Comment by tvdijen** [comment]
[debug_log.txt](https://github.com/OpenConext/OpenConext-manage/files/3922796/debug_log.txt)
[metadata.xml.txt](https://github.com/OpenConext/OpenConext-manage/files/3922799/metadata.xml.txt)
Here you go

**Comment by oharsta** [comment]
Strange, could not reproduce. Imported the IdP successfully with version 4.0.11. I also don't see the stack-trace in the attached debug.log. If I locally force an error then the logs show:
```
Dec  4 16:44:34 MANAGE-DWR: [http-nio-9393-exec-5] org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/manage/api].[dispatcherServlet] Servlet.service() for servlet [dispatcherServlet] in context with path [/manage/api] threw exception [Request processing failed; nested exception is java.lang.NullPointerException] with root cause

java.lang.NullPointerException: null
	at manage.control.ImportController.importXml(ImportController.java:76) ~[classes/:na]
	at manage.control.ImportController$$FastClassBySpringCGLIB$$e769561b.invoke(<generated>) ~[classes/:na]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204) ~[spring-core-4.3.14.RELEASE.jar:4.3.14.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:738) ~[spring-aop-4.3.14.RELEASE.jar:4.3.14.RELEASE]
.....Omitted the rest of the stack-trace
Dec  4 16:44:34 MANAGE-DWR: [http-nio-9393-exec-5] org.springframework.web.servlet.DispatcherServlet DispatcherServlet with name 'dispatcherServlet' processing POST request for [/manage/api/error]

```
Can you try again and capture the actual stack-trace witth line-numbers where the error occurred?

**Comment by tvdijen** [comment]
Sorry, the stack ended up in another log-file.. Here it is:

[trace.txt](https://github.com/OpenConext/OpenConext-manage/files/3936515/trace.txt)

**Comment by oharsta** [comment]
The error occurs because of the apparent differences in the JSON metadata schema's used. In the code we make assumptions about the presence of `SingleSignOnService_Binding`, `SingleLogoutService_Binding` and `AssertionConsumerService_Binding` enum definitions. See https://github.com/OpenConext/OpenConext-deploy/blob/master/roles/manage-server/files/metadata_configuration/saml20_idp.schema.json.j2#L5 and https://github.com/OpenConext/OpenConext-deploy/blob/master/roles/manage-server/files/metadata_configuration/saml20_sp.schema.json.j2#L6

**Comment by oharsta** [comment]
Release https://github.com/OpenConext/OpenConext-manage/releases/tag/4.0.12 with a more defensive strategy. However I do recommend putting the enum definitions in your JSON schema files.

**Comment by tvdijen** [comment]
Ah, I see! It's hard to keep up with schema-changes sometimes.. I must have missed this one!
