### ISSUE TITLE
Unable to set checkbox 'no_consent_required'

### ISSUE THREAD

**Issue by tvdijen** [OpenConext/OpenConext-manage#3]
Can't seem to check the checkbox for setting 'no_consent_required'.. Others can be checked fine.. Several browsers have been used to verify, but the result remains.

**Comment by oharsta** [comment]
Can not be reproduced. Have confirmed on the https://manage.test.surfconext.nl/ environment, the https://manage.test2.surfconext.nl/ environment and locally. Can you please specify which environment you have encountered this?

**Comment by tvdijen** [comment]
It's a local environment, based on `master` @ March 12th..
I can try the latest master, but I don't see any related changes since then..

**Comment by oharsta** [comment]
What is your node version and yarn version? I'm running:
```
okke@okke OpenConext-manage (master)$ yarn -v
1.6.0
okke@okke OpenConext-manage (master)$ node -v
v8.9.0
okke@okke OpenConext-manage (master)$ 
```
Also the checkboxes are dynamically rendered based on the JSON schema. I can't think of any reason why the one checkbox would not work while the others do.

**Comment by tvdijen** [comment]
Ah, that's quite the version gap:
```
[web@webapp-4 OpenConext-manage]# yarn -v
1.5.1
[web@webapp-4 OpenConext-manage]# node -v
v6.12.3
```
However, the latest `master` branch apparently fixed the issue...

**Comment by oharsta** [comment]
Ok. Glad that fixed the problem.

**Comment by tvdijen** [comment]
I was having this exact same issue again on a fresh install..
This time I 'fixed' it by using the zip from https://build.openconext.org/repository/public/releases/org/openconext/manage-gui/2.0.5/ instead of building it from release tarball... It really makes me wonder if I'm doing something wrong with the build..

`npm install` followed by `yarn build` should suffice, right?
