### ISSUE TITLE
Incorrect whitelist on JSON-import

### ISSUE THREAD

**Issue by tvdijen** [OpenConext/OpenConext-manage#32]
When importing SP-metadata using JSON import, where the metadata contains "state" : "prodaccepted", the whitelist dropdown will show entities for "testaccepted'.

The state is being displayed correctly on the 'Connections'-tab and flipping the state back&forth solves the glitch, so my guess is that the internal representation defaults to testaccepted instead of the imported JSON-value..

**Comment by oharsta** [comment]
Solved in https://github.com/OpenConext/OpenConext-manage/commit/ac2b05974a73c6acab44036d623a4ff1b90114e5#diff-8ca01c512096e6c304450326ac31b56fR448. New release will have to wait for other - internal - stories to be tested and confirmed.

**Comment by tvdijen** [comment]
Thanks!!
