### ISSUE TITLE
Feature-request:  show warning when no IDP's are connected

### ISSUE THREAD

**Issue by tvdijen** [OpenConext/OpenConext-manage#34]
Several times I have found myself in the situation where on the whitelist-tab the checkbox was false and no IDP was selected, leading to 'No organizations found'.
It usually happens when using a JSON-import containing whitelist-entries that do not exist on the receiving environment.

Since this is a detectable state, that AFAIK doesn't really serve a purpose, would it be possible to show a warning on saving the entity? That would allow me to fix it before hitting the Push-button.

**Comment by oharsta** [comment]
And how would one fix this situation? The only way is 'ticking' the allow all identity providers - which removes all the entities from the whitelist - and add the correct ones. And this warning should also be shown the other way around for consistency e.g. all imported service-providers / relying parties in the allowed-entities of the IdP that do not exists. And the message should be clearable as well. 

Begin september we start another development cycle for manage and then we'll discuss if we are going to implement this. I would welcome a PR in the meantime of course.

**Comment by tvdijen** [comment]
I was thinking something similar to the green bar that comes down when hitting the push-button..
But then orange and containing a warning that the IDP/SP is disconnected and is floating in limbo, when hitting the save-button.
Nothing too complicated, just a visual trigger that there may be an undesirable situation..

Regarding the PR, I'll see what I can do, but I'm not very familiar with Java tbh

**Comment by thijskh** [comment]
We are considering to redesign some parts to be able to better discern different states of entities ('exclude from push' 'imported from edugain' maybe some more) and I think we should be able to add to that some other basic info about the entity. I expect this early next year, probably not this year anymore.

**Comment by oharsta** [comment]
See https://github.com/OpenConext/OpenConext-manage/commit/60523d6a67f993b04e66095cd132e0409676ccde. A new release 6.0.3 will be made after the following story are accepted:

- https://www.pivotaltracker.com/story/show/173864433
- https://www.pivotaltracker.com/story/show/176412721

**Comment by oharsta** [comment]
Released https://github.com/OpenConext/OpenConext-manage/releases/tag/6.0.3.
