### ISSUE TITLE
How can the risk of feature toggle technical debt be reduced?

### ISSUE THREAD

**Issue by rmahdav** [OpenConext/OpenConext-manage#35]
Dear developers,

I, Rezvan Mahdavi Hezaveh (rmahdav@ncsu.edu), and my colleague, Nirav Ajmeri (najmeri@ncsu.edu), software engineering researchers from North Carolina State University are conducting an academic study of feature toggles and technical debt.
   
In our investigations on GitHub repositories, we noticed that you are using feature toggles in your repository. For instance, in this [commit](https://github.com/OpenConext/OpenConext-manage/commit/94262d9ef84761097cc5838bea88fc393a90b76c) a new feature toggle is added. In some of the changed files in this commit, two feature toggles named `show_oidc_rp` and `exclude_oidc_rp` are added with inverse values, two toggles for one purpose. It seems a redundancy in defining feature toggles. 

We would appreciate your collaboration in this study by answering an anonymous survey based upon your experience with the feature toggles. This survey has 20 questions and the estimated time to answer these questions is 10 minutes. 

The link to the survey is here: https://ncsu.qualtrics.com/jfe/form/SV_5BGE3wNDUtFQqMd

Once you start answering the survey questionnaire, you will have 24 hours to finish it.
As an appreciation for your time, we will conduct a random drawing and give $25 Amazon gift cards to five selected survey respondents. Also, we will share our results with you.

Thanks

**Comment by tvdijen** [comment]
The toggles you're referring to serve different purposes..  They could use a more descriptive name as one of the questions in your survey suggests! (I've filled it in as a developer for https://github.com/simplesamlphp/simplesamlphp)

**Comment by rmahdav** [comment]
Thanks for the clarification and thanks for your collaboration!

**Comment by thijskh** [comment]
Nonetheless, I think we have enough feature toggle experience to answer your questionnaire, so I did (and am of course hoping to win the gift card ;-)
