### ISSUE TITLE
PUSH contains two different json attributes related to use as NameID

### ISSUE THREAD

**Issue by phavekes** [OpenConext/OpenConext-manage#424]
[This issue is imported from pivotal - Originaly created at Jun 18, 2024 by Thijs Kinkhorst](https://www.pivotaltracker.com/story/show/187814449)

The EB PUSH contains two different fields, `useAsNameId` and `use_as_name_id` with different values.

```json
   "arp_attributes" : {
      "urn:mace:dir:attribute-def:cn" : [
         {
            "useAsNameId" : false,
            "use_as_name_id" : true,
            "value" : "*"
         }
      ]
   },
```

**Comment by thijskh** [comment]
Fixed in 323d5d8037dc9c64f60acd996eb80b95c3cd053b
