### ISSUE TITLE
Voeg kolom \'coin:interfed_source\' toe bij tab Whitelisting IdP\'s

### ISSUE THREAD

**Issue by phavekes** [OpenConext/OpenConext-manage#435]
[This issue is imported from pivotal - Originaly created at Jul 9, 2024 by andreklaver](https://www.pivotaltracker.com/story/show/187926026)

VOeg een kolom coin:interfed_source toe aan bij de Service Providers Whitelist opsomming bij IdP\'s. 

Dit om het mogelijk te maken een overizcht te creëren van eduGAIN SP\'s gekoppeld aan een IdP. Dit wordt gebruikt bij migraties van IdP\'s.

**Comment by thijskh** [comment]
Duplicate of #434
