### ISSUE TITLE
Feature request: Display `product.name` in title/tab

### ISSUE THREAD

**Issue by tvdijen** [OpenConext/OpenConext-manage#65]
We run OC/Manage for many customers and sometimes it's hard to distinguish them if you have many open tabs.
All tabs are named "Manage".. It would be really nice if the value from the `product.name` setting was used there so it's easier to distinguish the tabs.

**Comment by thijskh** [comment]
Are you sure about `product.name`? At least with us `product.name` is always "Manage" but `product.organization` is e.g. "SURFconext ACC"?

**Comment by oharsta** [comment]
https://github.com/OpenConext/OpenConext-manage/commit/1700fc5108f06f7775134f004d06afc1aec2d391. Better late than never

**Comment by tvdijen** [comment]
Awesome, thanks @oharsta !
