### ISSUE TITLE
Feature request: warn when removing an entity with active whitelist-references

### ISSUE THREAD

**Issue by tvdijen** [OpenConext/OpenConext-manage#66]
Some of my IDPs were replaced and got different entityIDs..
The old IDP trusts have been removed before cleaning up any whitelists configured on SPs.
This leads to warnings; "There are unknown entities connected to this Service Provider: <entityid>" and it's really a hassle to get rid of that warning.

My suggestion would be to either refuse removal of entities that have active references or _at least_ list and warn about the active references before removal.

**Update**:  I didn't actually remove the old IDP entity, but set the state to `testaccepted`..  I think however my point here still holds..

**Comment by thijskh** [comment]
I'm a bit confused what aspect you'd want to change exactly?
